spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: dev-user
    password: dev-password

logging:
  level:
    org.hibernate.SQL: DEBUG

time:
  expired:
    after: 14
